# Generated by Django 5.0.4 on 2024-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='VNPAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
