# Generated by Django 5.0.4 on 2024-05-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('VNPAY', 'VNPAY')], default='VNPAY', max_length=20),
        ),
    ]
