# Generated by Django 5.0.4 on 2024-05-06 20:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_category_options'),
        ('favoritebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritebook',
            unique_together={('user', 'book')},
        ),
    ]
