# Generated by Django 5.0.4 on 2024-05-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
