# Generated by Django 5.0.4 on 2024-04-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
