# Generated by Django 5.0.4 on 2024-05-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating_count',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
