# Generated by Django 5.0.4 on 2024-05-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
