# Generated by Django 5.0.4 on 2024-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_promotion_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, choices=[('Paperback', 'Paperback'), ('Hardback', 'Hardback')], max_length=255, null=True),
        ),
    ]
