# Generated by Django 5.0.3 on 2024-04-08 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
