# Generated by Django 5.0.3 on 2024-04-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_category_created_at_publisher_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
    ]
