# Generated by Django 5.0.3 on 2024-04-08 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_promotion_alter_book_author_alter_book_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 15, 41, 11, 17108, tzinfo=datetime.timezone.utc)),
        ),
    ]
