# Generated by Django 5.0.3 on 2024-04-08 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 0, 49, 796314, tzinfo=datetime.timezone.utc)),
        ),
    ]
