# Generated by Django 5.0.3 on 2024-04-09 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 4, 35, 27, 277018, tzinfo=datetime.timezone.utc)),
        ),
    ]
