# Generated by Django 5.0.3 on 2024-04-09 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_discounted_price_alter_promotion_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discounted_price',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 7, 2, 19, 278239, tzinfo=datetime.timezone.utc)),
        ),
    ]
