# Generated by Django 5.0.4 on 2024-05-04 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Phone number must be between 10 and 15 digits.')]),
        ),
    ]
